global:
  coroutine:
    enable: true
  threadmodel:
    fiber:
      - instance_name: fiber_instance
        concurrency_hint: 8
        scheduling_name: "v2"

plugins:
  log:
    default:													#新版日记系统
      - name: default
        min_level: 2 # 0-trace, 1-debug, 2-info, 3-warn, 4-error, 5-critical
        format: "[%Y-%m-%d %H:%M:%S.%e] [thread %t] [%l] [%@] %v"
        mode: 3 # 1-同步, 2-异步, 3-极速
        sinks:
          local_file:
            eol: true
            filename: unittest.log
            roll_size: 10000000
            reserve_count: 5
